// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcTJB8uQVuSre4q-AAK-wqHgSJEG8whdo',
    appId: '1:1047205530970:web:f056de0897707fd8e93763',
    messagingSenderId: '1047205530970',
    projectId: 'cfoapp-1793e',
    authDomain: 'cfoapp-1793e.firebaseapp.com',
    storageBucket: 'cfoapp-1793e.appspot.com',
    measurementId: 'G-10ZDZLJF5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKTuoLjhRY1Lq_RVLkFcHxNrhI3gCW_Sc',
    appId: '1:1047205530970:android:3dc7f69ee748e57ce93763',
    messagingSenderId: '1047205530970',
    projectId: 'cfoapp-1793e',
    storageBucket: 'cfoapp-1793e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7GJkNxxTqb9J3OH7XOo87MWZQyzLxCBw',
    appId: '1:1047205530970:ios:2be75bb01e26f211e93763',
    messagingSenderId: '1047205530970',
    projectId: 'cfoapp-1793e',
    storageBucket: 'cfoapp-1793e.appspot.com',
    iosBundleId: 'com.cfo.app',
  );
}
